version: "3.3"

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db:/var/lib/postgresql/data
  web:
    build: ./django
    ports:
      - "8000:8000"
    links:
      - algorithm
    volumes:
      - ./django:/code
    depends_on:
      - db
    command: bash -c "python /code/manage.py migrate --noinput && python /code/manage.py runserver 0.0.0.0:8000"

  algorithm:
    build: ./flask
    ports:
      - "5000:5000"
    volumes:
      - ./flask:/code
    depends_on:
      - db
      - redis
    command: bash -c "export FLASK_APP=app/services.py && flask run --host 0.0.0.0 --port 5000"

  algorithm_celery:
    build: ./flask
    volumes:
      - ./flask:/code
    links:
      - redis
    depends_on:
      - redis
    command: bash -c "cd app && celery -A services.celery worker -l info"
